FROM public.ecr.aws/lambda/python:3.11

ENTRYPOINT []

RUN pip install --upgrade pip && \
    pip install \
        fastapi \
        requests \
        pydantic \
        mangum \
        --only-binary=:all: \
        -t /opt/python
